name: Netlify deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
